### ISSUE TITLE
StatusBar translucent with under the image and other things ...

### ISSUE THREAD

**Issue by Angelk90** [cesardeazevedo/react-native-collapsing-toolbar#18] opened 2018-07-12 12:07 UTC
Hi @cesardeazevedo : 
I have an example: https://github.com/cesardeazevedo/react-native-collapsing-toolbar/blob/master/example/index.android.js

- I did something like this:
`        <StatusBar backgroundColor={'rgba(255, 255, 255, 0.15)'} translucent />
`

and I removed the height of the statusBar:

So under the status bar you could see the image, but the problem I need to give the separation to the title and Icon.ToolbarAndroid, there is a way?

- If I remove Icon.ToolbarAndroid, it gives me problems, I can not see the title anymore, how come?

- in the NestedScrollView, I put a very long text, but it puts a kind of marginbottom, how come?

Code: 

```

import React, { Component } from 'react';
import {
  Text,
  View,
  Image,
  Animated,
  FlatList,
  TextInput,
  StatusBar,
  ScrollView,
  StyleSheet,
  Dimensions,
} from 'react-native';

import Icon from 'react-native-vector-icons/Ionicons';

import {
  AppBarLayout,
  CoordinatorLayout,
  CollapsingToolbarLayout,
  CollapsingParallax,
} from 'react-native-collapsing-toolbar';

import NestedScrollView from 'react-native-nested-scroll-view';

const HEADER_HEIGHT = 250;
const { width } = Dimensions.get('window');

var text =
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec placerat, neque vitae accumsan tempus, enim lectus viverra metus, id lacinia magna lorem sed velit. Sed at turpis diam. Integer semper feugiat tempor. Vivamus sit amet ante quis nulla interdum iaculis. Mauris in justo odio. Fusce molestie mi purus, ac suscipit lorem finibus et. Phasellus sed rutrum ligula. Sed at tellus maximus, dignissim mi vitae, tristique magna.Proin laoreet porta condimentum. Ut lorem risus, sagittis ac tortor a, vehicula dapibus erat. Vivamus sit amet vestibulum velit, eu sodales nisl. Donec eget elit ut felis euismod accumsan. In id ligula et ex congue malesuada id at ligula. In ut neque in neque lobortis scelerisque. Morbi at purus non lorem euismod ultricies sed eu arcu. Aliquam non metus finibus, aliquam augue vel, tincidunt lorem. Integer luctus risus aliquet erat condimentum, eu fringilla magna hendrerit.Quisque vel lectus vel odio commodo sodales sit amet in lacus. Donec nec interdum magna, et rutrum velit. Phasellus leo est, posuere a mauris quis, facilisis mattis quam. Integer sodales quam metus, et finibus lorem rutrum vitae. Mauris quis urna ac ligula pellentesque lobortis pretium eget enim. Nulla convallis placerat erat in euismod. Nulla facilisi. Mauris sodales ipsum nec vehicula finibus. Cras eu volutpat quam. Duis maximus finibus ornare. Quisque sapien enim, pretium vel magna a, egestas feugiat sapien. Proin ornare risus ut est pellentesque congue. Proin vestibulum velit sit amet nunc molestie, quis lobortis lorem fermentum. Donec eget arcu et enim tincidunt hendrerit. In convallis leo tincidunt, tincidunt sapien sit amet, mattis elit. Morbi pellentesque orci non nisi sollicitudin congue.In vulputate urna ex, eget egestas sapien dapibus at. Nulla sed mattis augue. Sed scelerisque ut est et ultrices. Vestibulum ut nisl ac quam euismod luctus ac id lectus. Curabitur dolor neque, blandit quis fringilla sit amet, malesuada nec ante. Nulla facilisi. Nullam egestas, tortor sed accumsan ullamcorper, lacus est hendrerit elit, sed luctus arcu sapien vel quam. Aliquam sollicitudin sed tellus fringilla convallis. Vestibulum vitae tincidunt tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum lacinia eros purus, vel varius eros eleifend porttitor. Nam mollis leo in laoreet ultrices. In pellentesque lorem in sagittis vehicula. Duis ullamcorper, diam pellentesque dictum luctus, erat diam elementum justo, non ornare massa dui sollicitudin enim.Curabitur sed tempor mauris, id viverra nibh. Nullam cursus ante eget odio consequat ullamcorper. Nulla ac mollis lectus. Aliquam porttitor nec sapien dapibus ultrices. Morbi auctor ante in orci consequat feugiat. Duis sit amet viverra libero. Pellentesque et massa sit amet diam bibendum consectetur sit amet vitae tellus. Duis viverra ex eget vehicula posuere. Fusce quis accumsan magna. Nunc cursus bibendum turpis, ac consectetur nulla viverra vel. Ut varius faucibus quam, sed interdum nunc euismod in. Ut interdum tempus odio, in euismod magna tincidunt sit amet. Phasellus convallis justo aliquet, vestibulum magna eget, finibus lorem. Nam blandit sit amet nisi vitae gravida. Donec tempus pharetra odio et vestibulum. Nunc nec neque odio.';

export default class RNCollapsingToolbar extends Component {
  state = {
    icon: null,
    scrollY: new Animated.Value(0),
  };

  componentDidMount() {
    // Load icon from react-native-vector-icons manually
    Icon.getImageSource('md-menu', 24, '#ffffff').then(source => {
      this.setState({ icon: source });
    });
  }

  captureAppBarRef = ref => {
    this.appBar = ref;
  };

  handleActionSelected = action => {
    return action === 0
      ? this.appBar.show()
      : action === 1
        ? this.appBar.hide()
        : null;
  };

  handleOffsetChanged = e => {
    Animated.event([{ nativeEvent: { offset: this.state.scrollY } }])(
      e,
      this.state
    );
  };

  render() {
    const { scrollY, icon } = this.state;

    return (
      <View style={styles.container}>
        <StatusBar backgroundColor={'rgba(255, 255, 255, 0.15)'} translucent />
        <View style={styles.statusBar} />
        <CoordinatorLayout>
          <AppBarLayout
            ref={this.captureAppBarRef}
            onOffsetChanged={this.handleOffsetChanged}
            style={styles.appbar}>
            <CollapsingToolbarLayout
              title="Le 3 regole fondamentali per un primo incontro"
              contentScrimColor="#ff5bc5"
              expandedTitleColor="white"
              collapsedTitleTextColor="white"
              expandedTitleGravity="BOTTOM"
              scrimVisibleHeightTrigger={100}
              scrimAnimationDuration={400}
              expandedTitleMarginStart={22}
              expandedTitleMarginBottom={22}
              scrollFlags={
                AppBarLayout.SCROLL_FLAG_SCROLL |
                AppBarLayout.SCROLL_FLAG_EXIT_UNTIL_COLLAPSED
              }>
              <CollapsingParallax parallaxMultiplier={0.6}>
                <View collapsable={false} style={styles.parallaxView}>
                  <Image
                    source={{
                      uri:
                        'https://imgix.bustle.com/elite-daily/2017/06/20162256/man-woman-first-date-smiling.jpg',
                    }}
                    style={styles.image}
                  />
                </View>
              </CollapsingParallax>
              <Icon.ToolbarAndroid
                iconColor="white"
                onActionSelected={this.handleActionSelected}
                actions={[{ title: 'Show' }, { title: 'Hide' }]}
              />
            </CollapsingToolbarLayout>
          </AppBarLayout>
          <NestedScrollView>
            <View style={styles.box}>
              <Text style={styles.text}>{text}</Text>
            </View>
          </NestedScrollView>
        </CoordinatorLayout>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    paddingBottom: 550,
  },
  appbar: {
    height: HEADER_HEIGHT,
    backgroundColor: 'black',
  },
  parallaxView: {
    height: HEADER_HEIGHT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  box: {
    //alignItems: 'center',
    //justifyContent: 'center',
    //height: 100,
    flex: 1,
    borderRadius: 2,
//marginVertical: 8,
  //  marginHorizontal: 10,
    backgroundColor: '#fff',
    elevation: 2,
    padding: 5,
  },
  image: {
    width,
    height: HEADER_HEIGHT,
    position: 'absolute',
    backgroundColor: '#000',
    opacity: 0.65,
  },
  statusBar: {
    //  height: 24,
    //marginTop: 24
  },
});

```

Here I put a complete example, you just have to download the zip file.
link: https://snack.expo.io/S1G1ZlHQX

**Comment by cesardeazevedo** [comment] 2018-07-13 03:57
Hi, i hope i understood your issue correctly, 

I've successfully tested your example, and what i could understand, is that you want to show the image under the StatusBar, and to achieve that you removed the `statusBar` view (which was just used to add some space), right.

After run your example, i released that the toolbar didn't fit well with under the status bar, like the image bellow.
![screen shot 2018-07-12 at 23 51 31](https://user-images.githubusercontent.com/5366959/42670171-aca45ee2-862f-11e8-8f86-1802971a2391.png)

Is this your issue? if does, well, i haven't found a solution so far, i've played with adding `translucent` props to `AppBarLayout`, `CollapsingToolbarLayout`, `CollapsingParallax` respectively, and manually add some margin on the native side, but i haven't be able to adjust the parallax view under the status bar, so this would require some research and time.

Now, if doesn't, and i didn't understood what you say with `I need to give the separation to the title and Icon.ToolbarAndroid.`, what you mean with the "separation" of the title Icon.ToolbarAndroid?

> If I remove Icon.ToolbarAndroid, it gives me problems, I can not see the title anymore, how come?

Why do you want to remove the ToolbarAndroid? the ToolbarAndroid is required to work with the CollapsingToolbarLayout even though the title is set on the CollapsingToolbarLayout.

> in the NestedScrollView, I put a very long text, but it puts a kind of marginbottom, how come?

Is because there's `paddingBottom: 550` on the container style, which must be a better way to handle that, or maybe a dynamic padding to fits the content and be able to scroll as expected.

**Comment by Angelk90** [comment] 2018-07-13 04:48
@cesardeazevedo : 
1) Yes, the effect I want to achieve is what you see in the image, I've tried everything, so at the moment there is no solution?
2) I want to remove the side menu, ie the black points that you see, in the end I realized that just do it like this:
`<Icon.ToolbarAndroid />
`But I'm not understanding if: `<Icon.ToolbarAndroid iconColor = "white"`
Why do you see it in black?
3) I did not understand why there must be this PaddingBottom.

Take a look at the gif, in this case
```
container: {
    paddingBottom: 550,
  },
```

http://i.imgur.com/HN696J0.gif

As you can see there are two different cases:
1) Little text, so the whole container is not covered.
2) A lot of text, some strange events happen:
- There is a certain slowing down in sliding, both from top to bottom and from bottom to top.
- The container is not covered all.
- This I do not know how to explain it well or how you can replicate it, but I try the same.

When I scroll from bottom to top and in the meantime release / raise the finger from the scroll, I get the effect that you see in the image, that is not going forward.

I do not know if I explained myself well.

Here I put a complete example, you just have to download the zip file.
link: https://snack.expo.io/S1G1ZlHQX

**Comment by cesardeazevedo** [comment] 2018-07-13 07:40
> Yes, the effect I want to achieve is what you see in the image, I've tried everything, so at the moment there is no solution?

No, there's no solution yet, as i already explained.

> I want to remove the side menu

If you want to remove the 3 dots, just remove the `actions` property.

> Why do you see it in black?

I don't know why they are black, `ToolbarAndroid` is not part of this library, so i can't help with it, refer to these issues.
https://github.com/oblador/react-native-vector-icons/issues/502
https://github.com/facebook/react-native/issues/5483

> I did not understand why there must be this PaddingBottom.

The paddingBottom is just a way to compensate the height added by the AppBarLayout and fits the main content on the screen, it's just the they way the CollapsingToolbarLayout works behind the scenes, it keeps the height even when it collapses, or some kind of, is hard to explain.

I already tried to applying LayoutParams.WRAP_CONTENT, but didn't help that much,  `CoordinatorLayouts`, `AppBarLayout`, `NestedScrollView` is **NOT** something easy to work nicely with react-native, and is not something common out there, some things are much better to play yourself than trying to explain, i don't have answers for everything

A better approach would be to set container with the height of the screen and subtracted by the HEADER_HEIGHT (`height: height - HEADER_HEIGHT`), that could work just fine.

> Little text, so the whole container is not covered.

Use a minHeight to cover the screen.

> The container is not covered all.

Please, replace the paddingBottom with this.

```js
const HEADER_HEIGHT = 250
const { height } = Dimensions.get('window')

const styles = StyleSheet.create({
  container: {
    height: height - HEADER_HEIGHT,
  },
})
```

I hope it helps.

**Comment by Angelk90** [comment] 2018-07-14 09:57
@cesardeazevedo : 
1) I thought of something like this:
Since the status bar is about 24 as a dimension, add the size of the toolbar (56) to 24.
So I tried to put in CollapsingToolbarLayout: `height = {80}`
but it seems that the props do not work.

So I modified the file: `CollapsingToolbarLayoutManager`
`  private int height = 80;
`This means that the height changes.

56:
![schermata_2018-07-14-10-50-06-297](https://user-images.githubusercontent.com/20476002/42723381-ef1ebdfc-875c-11e8-8c10-bb475bb7b49f.jpeg)

80:
![schermata_2018-07-14-10-49-04-518](https://user-images.githubusercontent.com/20476002/42723383-ef4b3896-875c-11e8-8609-6a82daf24b10.jpeg)


Now the problems are these:
a) to outline the title, the probable solution even if a little dirty, to put to the title a paddingTop: 24
b) `<Icon.ToolbarAndroid` it does not move, I did a test but it does not seem to work, maybe I'm wrong.

I'm trying to find official documentation, but I find nothing useful.

2) I think I found a solution, I did so:
```
<Icon.ToolbarAndroid
iconColor = "white"
overflowIconName = "md-more"
.... />
```

3) I tried as you say, it does not work, on the contrary the situation worsens.

Let's try to solve problem 1 first.
What do you think about it?

**Comment by cesardeazevedo** [comment] 2018-07-14 10:54
Trying to push the Toolbar with `paddingTop` or `marginTop` won't work on the react-native side, this is how you can achieve that (https://github.com/cesardeazevedo/react-native-bottom-sheet-behavior/blob/master/android/src/main/java/com/bottomsheetbehavior/MergedAppBarLayoutManager.java#L50-L57).

![translucent](https://user-images.githubusercontent.com/5366959/42723680-ced5f3f4-8738-11e8-922a-c7fbbe9ace03.gif)

But doesn't work at all, the problem is related to the CollapsingParallax that is not rendering behind the statusbar, which would require a better investigation playing around with the margins and maybe with `setFitsSystemWindows`, but i really don't have much time to investigate it, sorry.

Try to search about CollapsingToolbar + translucent, maybe you will find something more quickly than me.

**Comment by Angelk90** [comment] 2018-07-14 12:54
How did you do this?
![](https://user-images.githubusercontent.com/5366959/42723680-ced5f3f4-8738-11e8-922a-c7fbbe9ace03.gif)

How did you do this?

I'm trying to do such a thing, but it seems that this.state.scrollY._value in rendering never changes.



```
  render() {
    const { scrollY, icon } = this.state;
    const { data } = this.props.navigation.state.params;
    let status = (<StatusBar backgroundColor={'#d19a18'} />);
    let status2 = (<StatusBar backgroundColor={'rgba(255, 255, 255, 0.15)'} translucent />);
    console.log(scrollY._value)
    return (
      <View style={[styles.container,{}]}>
        {this.state.scrollY._value<-380 ? status : status2 }
```

**Comment by Angelk90** [comment] 2018-07-16 08:05
@cesardeazevedo : How did you do this?
![](https://user-images.githubusercontent.com/5366959/42723680-ced5f3f4-8738-11e8-922a-c7fbbe9ace03.gif)


I did it, but it's a dirty solution.
```

  handleOffsetChanged = e => {
    Animated.event([{ nativeEvent: { offset: this.state.scrollY } }])(
      e,
      this.state
    );
    this.setState({ value: this.state.scrollY._value });
  };

  render() {
    const { value, scrollY, icon } = this.state;
    const { data } = this.props.navigation.state.params;
    let status = (<StatusBar backgroundColor={'#2196F3'} barStyle="light-content" />);
    let status2 = (<StatusBar backgroundColor={'rgba(255, 255, 255, 0.15)'} translucent />);
    return (
      <View style={[styles.container,{}]}>
        {value<-380 ? status : status2 }
```


What do you think about it?

**Comment by cesardeazevedo** [comment] 2018-07-16 08:54
Deleting your comment and posting again won't make me answer your issue quickly, quite the opposite, so be patient.

> How did you do this?

I pointed a link on my previous comment, but as i already explained, doesn't solved CollapsingParallax issue.

I really don't what to think about your "dirty solution", if it's a dirty solution, is not something that i am interesting at looking at, i prefer to look at better solutions that scale for the library, but if your "solution" solves your problem in the short term, i am totally fine with it.

My suggestion is just use a background on the statusBar like the example, and back the statusBar height that you removed, that things just work fine.

Right now i am more focused on keeping the library working on new react-native versions, and **translucent statusBar is just a very small detail that i am not really interested for now**.

> When I scroll from bottom to top and in the meantime release / raise the finger from the scroll, I get the effect that you see in the image, that is not going forward.

Regarding the scroll issue when scrolling upwards, it will be fixed on the next version of the [react-native-nested-scroll-view](https://github.com/cesardeazevedo/react-native-nested-scroll-view)

**Comment by Angelk90** [comment] 2018-07-16 16:18
@cesardeazevedo :  ![](https://i.imgur.com/EwFPMjQ.gif)

**Comment by cesardeazevedo** [comment] 2018-07-16 16:47
Well, maybe because of your "dirty solution"? 🤣 

I am sorry, but i can't help you further, i really don't know what you doing or trying to do.

Translucent statusBar is not supported yet, and there's no plan to implement it anytime soon, and i **won't** and **can't** help you with any work around.

I am going to close the issue, and i recommend you to ask for help on stackoverflow or some other place.

I also recommend you update the react-native-nested-scroll-view to `7.0.0` to avoid any issues when scrolling with support library 26.

**Closed by cesardeazevedo** 2018-07-16 16:47 UTC

**Comment by Angelk90** [comment] 2018-07-18 14:19
@cesardeazevedo :  What software or app do you use to record the device screen?

**Comment by cesardeazevedo** [comment] 2018-07-20 08:44
I use [Licecap](https://www.cockos.com/licecap/)
